#include "./contenido/planteamiento_problema.typ"
#include "./contenido/objetivos.typ"
// #include "./contenido/hipotesis.typ"
#include "./contenido/antecedentes.typ"
// #include "./contenido/justificacion.typ"
#include "./contenido/marco_teorico.typ"
// #include "./contenido/alcance_limitaciones.typ"
#include "./contenido/metodologia.typ"
#include "./contenido/experimentacion.typ"
#include "./contenido/conclusiones.typ"
#include "./contenido/anexos.typ"
